name: Nightly - Jahia Snapshot

on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *"

jobs:
  integration-tests-standalone:
    name: Integration Tests (Standalone)
    secrets: inherit
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    with:
      module_id: siteSettings
      module_branch: main
      provisioning_manifest: provisioning-manifest-snapshot.yml
      incident_service: siteSettings-JahiaSN
      jahia_image: ghcr.io/jahia/jahia-ee-dev:8-SNAPSHOT
      artifact_prefix: siteSettings
      testrail_project: Site Settings
      timeout_job: 45
      timeout_step: 20